### ISSUE TITLE
link cnn failed

### ISSUE THREAD

**Issue by lishoubin** [AlfredXiangWu/cnnFace#2]
>LINK : fatal error C1047: 对象或库文件“E:\face\cnnFace\cnnlib\cnnAPI_Release.lib”是使用比创建其他对象所用编译器旧的编译器创建的；请重新生成旧的对象和库

可能是编译器版本对不上，能否将您使用的cnn的地址贴出来，大家自己编译下？

**Comment by AlfredXiangWu** [comment]
这个库是我自己写的，因为某些原因不方便公开，见谅

**Comment by lishoubin** [comment]
@AlfredXiangWu  谢谢.
